### ISSUE TITLE
Wczytywanie i zapisywanie

### ISSUE THREAD

**Issue by michal17** [manio143/ShadowsOfShadows#41]
Robimy cztery sloty zapisywania gry, jeśli pusty to napisane `(empty)` w.p.p podana jest data zapisu.

Na dysku przechowujemy w podfolderze "savedgames" pliki `#.sav`, gdzie # to numer 1-4

**Comment by manio143** [comment]
Mimo, że zmeargowaliśmy PR #51 to nadal nie serializujemy skilli w graczu w sensowny sposób
https://github.com/manio143/ShadowsOfShadows/blob/3c1b8bf2695129f33172380106b068aad4a9552a/src/Entities/Player.cs#L21-L22

Takie coś:
https://github.com/manio143/ShadowsOfShadows/blob/3c1b8bf2695129f33172380106b068aad4a9552a/src/Entities/Player.cs#L51-L73
Nie powinno być w graczu, bo to jest logika serializacji a nie gry. Zobacz czy na pewno słownik się nie serializuje, a jeśli nie to trzeba stworzyć jakąś klasę pośrednią, albo się jakoś wczepić do deserializera, żeby to było dobrze odseparowane.

**Comment by manio143** [comment]
Closed via #67
