### ISSUE TITLE
TimedConsumable effect list in Player

### ISSUE THREAD

**Issue by michal17** [manio143/ShadowsOfShadows#42]
Chcemy listę Zjedzonych TimedConsumables w Playerze wraz z wywołaniem ich metody Update

Do tego w EquipmentMessage trzeba dodać ten element do tej listy.

**Comment by dkaluza** [comment]
Hmm dlaczego akurat w EquimentMessage?

**Comment by manio143** [comment]
Bo w nim go aktywujemy

**Comment by manio143** [comment]
Dobra, widzę, że zrobiłeś inaczej. Jest git 😊
