### ISSUE TITLE
Create additional Consoles

### ISSUE THREAD

**Issue by dkaluza** [manio143/ShadowsOfShadows#7]
* MessageConsole (bottom)
* Inventory (right)

**Comment by manio143** [comment]
Jednym z elementów mojego pull requesta będzie przeniesienie gry na SadConsole 6.0 i MonoGame 3.6, przez co nieco się to wydłuży, ponieważ MonoGame ma obecnie zepsutą paczkę NuGet.

Informacje jak sobie z tym poradzić na razie https://github.com/MonoGame/MonoGame/issues/5531
